apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  SECRET_KEY: "devsecops-demo-secret"
  JWT_SECRET_KEY: "devsecops-demo-jwt"
  POSTGRES_PASSWORD: "devpassword"
  POSTGRES_USER: "devuser"
  POSTGRES_DB: "eventsdb"
 
